# .streamlit/secrets.toml 
# Add this file to your Streamlit app for MongoDB connection

# MongoDB connection string
MONGODB_URI = "mongodb+srv://username:password@cluster.mongodb.net/employee_survey?retryWrites=true&w=majority"

# Alternative local MongoDB connection
# MONGODB_URI = "mongodb://localhost:27017/"
